//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedElems.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpeedElems.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Don&apos;t tap a flaming Fire Element a second time! It burns....
        /// </summary>
        internal static string AbusedDoublePressedFire {
            get {
                return ResourceManager.GetString("AbusedDoublePressedFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is no more Fire to evaporate the remaining Element!.
        /// </summary>
        internal static string AbusedNoMoreFireForWater {
            get {
                return ResourceManager.GetString("AbusedNoMoreFireForWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Audio.
        /// </summary>
        internal static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bio.
        /// </summary>
        internal static string Bio {
            get {
                return ResourceManager.GetString("Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coming soon ....
        /// </summary>
        internal static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Easy (3 sec / round).
        /// </summary>
        internal static string DelayEasy3sec {
            get {
                return ResourceManager.GetString("DelayEasy3sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delays between rounds.
        /// </summary>
        internal static string DelaysBetweenRounds {
            get {
                return ResourceManager.GetString("DelaysBetweenRounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Standard (2 sec / round).
        /// </summary>
        internal static string DelayStandard2sec {
            get {
                return ResourceManager.GetString("DelayStandard2sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Difficulty.
        /// </summary>
        internal static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Effects.
        /// </summary>
        internal static string Effects {
            get {
                return ResourceManager.GetString("Effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Electricity.
        /// </summary>
        internal static string Electricity {
            get {
                return ResourceManager.GetString("Electricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Electricity Duo.
        /// </summary>
        internal static string ElectricityDuo {
            get {
                return ResourceManager.GetString("ElectricityDuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Electricity Trio.
        /// </summary>
        internal static string ElectricityTrio {
            get {
                return ResourceManager.GetString("ElectricityTrio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Element of .
        /// </summary>
        internal static string ElementCount1 {
            get {
                return ResourceManager.GetString("ElementCount1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Double Elements of .
        /// </summary>
        internal static string ElementCount2 {
            get {
                return ResourceManager.GetString("ElementCount2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Triple Elements of .
        /// </summary>
        internal static string ElementCount3 {
            get {
                return ResourceManager.GetString("ElementCount3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quadruple Elements of .
        /// </summary>
        internal static string ElementCount4 {
            get {
                return ResourceManager.GetString("ElementCount4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Elements.
        /// </summary>
        internal static string Elements {
            get {
                return ResourceManager.GetString("Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Elements per round.
        /// </summary>
        internal static string ElementsPerRound {
            get {
                return ResourceManager.GetString("ElementsPerRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Four different.
        /// </summary>
        internal static string Elems_FourDifferent {
            get {
                return ResourceManager.GetString("Elems_FourDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Three different.
        /// </summary>
        internal static string Elems_ThreeDifferent {
            get {
                return ResourceManager.GetString("Elems_ThreeDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Two different.
        /// </summary>
        internal static string Elems_TwoDifferent {
            get {
                return ResourceManager.GetString("Elems_TwoDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fire.
        /// </summary>
        internal static string Fire {
            get {
                return ResourceManager.GetString("Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ground.
        /// </summary>
        internal static string Ground {
            get {
                return ResourceManager.GetString("Ground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ice.
        /// </summary>
        internal static string Ice {
            get {
                return ResourceManager.GetString("Ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Music.
        /// </summary>
        internal static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tricks :.
        /// </summary>
        internal static string Tricks {
            get {
                return ResourceManager.GetString("Tricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Three parched ground :(.
        /// </summary>
        internal static string Tricks_3ParchedGround {
            get {
                return ResourceManager.GetString("Tricks_3ParchedGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à press+press+press+press.
        /// </summary>
        internal static string Tricks_4Pressed {
            get {
                return ResourceManager.GetString("Tricks_4Pressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mu-Mu-Mu-Mu-Multi-Kill !!!.
        /// </summary>
        internal static string Tricks_5Kills {
            get {
                return ResourceManager.GetString("Tricks_5Kills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click on itself....
        /// </summary>
        internal static string Tricks_CheckBox {
            get {
                return ResourceManager.GetString("Tricks_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A charcoal!.
        /// </summary>
        internal static string Tricks_FireCoal {
            get {
                return ResourceManager.GetString("Tricks_FireCoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wet ground???.
        /// </summary>
        internal static string Tricks_GroundWet {
            get {
                return ResourceManager.GetString("Tricks_GroundWet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Abandoned water :(.
        /// </summary>
        internal static string Tricks_NoFireForWater {
            get {
                return ResourceManager.GetString("Tricks_NoFireForWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Push the ground!.
        /// </summary>
        internal static string Tricks_PushTheGround {
            get {
                return ResourceManager.GetString("Tricks_PushTheGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The SPEED is fast ~~~.
        /// </summary>
        internal static string Tricks_SpeedFastWithWind {
            get {
                return ResourceManager.GetString("Tricks_SpeedFastWithWind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Intense Wind ....
        /// </summary>
        internal static string Tricks_Wind5cm {
            get {
                return ResourceManager.GetString("Tricks_Wind5cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pinch a Bio Element with two fingers to compress it!.
        /// </summary>
        internal static string TutorialBio {
            get {
                return ResourceManager.GetString("TutorialBio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connect two Electricity Elements by pressing them at the same time!.
        /// </summary>
        internal static string TutorialElectricity2 {
            get {
                return ResourceManager.GetString("TutorialElectricity2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connect three Electricity Elements by pressing them at the same time!.
        /// </summary>
        internal static string TutorialElectricity3 {
            get {
                return ResourceManager.GetString("TutorialElectricity3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press once on a Fire Element to ignite it!.
        /// </summary>
        internal static string TutorialFire {
            get {
                return ResourceManager.GetString("TutorialFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Double press a Ground Element to explode it!.
        /// </summary>
        internal static string TutorialGround {
            get {
                return ResourceManager.GetString("TutorialGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At the top you can see the number of rounds in a level: there are three left!.
        /// </summary>
        internal static string TutorialRoundNumber {
            get {
                return ResourceManager.GetString("TutorialRoundNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At the bottom you can see the time allocated for a round: be careful, it will go faster!.
        /// </summary>
        internal static string TutorialRoundTimer {
            get {
                return ResourceManager.GetString("TutorialRoundTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Be careful, there are three Elements ....
        /// </summary>
        internal static string TutorialThreeElems {
            get {
                return ResourceManager.GetString("TutorialThreeElems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Be careful, there are two Elements ....
        /// </summary>
        internal static string TutorialTwoElems {
            get {
                return ResourceManager.GetString("TutorialTwoElems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move a Water element over one Fire Element to make it evaporate!.
        /// </summary>
        internal static string TutorialWater1 {
            get {
                return ResourceManager.GetString("TutorialWater1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move an Ice element over two Fire Elements to make it evaporate!.
        /// </summary>
        internal static string TutorialWater2 {
            get {
                return ResourceManager.GetString("TutorialWater2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move a Wind Element to scramble it!.
        /// </summary>
        internal static string TutorialWind {
            get {
                return ResourceManager.GetString("TutorialWind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Levels unlocked on Standard will be automaticaly unlocked on Easy.
        /// </summary>
        internal static string UnlockedLevels {
            get {
                return ResourceManager.GetString("UnlockedLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Water.
        /// </summary>
        internal static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wind.
        /// </summary>
        internal static string Wind {
            get {
                return ResourceManager.GetString("Wind", resourceCulture);
            }
        }
    }
}
