//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedElems.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpeedElems.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t tap a flaming Fire Element a second time! It burns....
        /// </summary>
        internal static string AbusedDoublePressedFire {
            get {
                return ResourceManager.GetString("AbusedDoublePressedFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no more Fire to evaporate the remaining Element!.
        /// </summary>
        internal static string AbusedNoMoreFireForWater {
            get {
                return ResourceManager.GetString("AbusedNoMoreFireForWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        internal static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio.
        /// </summary>
        internal static string Bio {
            get {
                return ResourceManager.GetString("Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming soon ....
        /// </summary>
        internal static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy (3 sec / round).
        /// </summary>
        internal static string DelayEasy3sec {
            get {
                return ResourceManager.GetString("DelayEasy3sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delays between rounds.
        /// </summary>
        internal static string DelaysBetweenRounds {
            get {
                return ResourceManager.GetString("DelaysBetweenRounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard (2 sec / round).
        /// </summary>
        internal static string DelayStandard2sec {
            get {
                return ResourceManager.GetString("DelayStandard2sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        internal static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effects.
        /// </summary>
        internal static string Effects {
            get {
                return ResourceManager.GetString("Effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity.
        /// </summary>
        internal static string Electricity {
            get {
                return ResourceManager.GetString("Electricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity Duo.
        /// </summary>
        internal static string ElectricityDuo {
            get {
                return ResourceManager.GetString("ElectricityDuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity Trio.
        /// </summary>
        internal static string ElectricityTrio {
            get {
                return ResourceManager.GetString("ElectricityTrio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element of .
        /// </summary>
        internal static string ElementCount1 {
            get {
                return ResourceManager.GetString("ElementCount1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Elements of .
        /// </summary>
        internal static string ElementCount2 {
            get {
                return ResourceManager.GetString("ElementCount2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triple Elements of .
        /// </summary>
        internal static string ElementCount3 {
            get {
                return ResourceManager.GetString("ElementCount3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadruple Elements of .
        /// </summary>
        internal static string ElementCount4 {
            get {
                return ResourceManager.GetString("ElementCount4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements.
        /// </summary>
        internal static string Elements {
            get {
                return ResourceManager.GetString("Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements per round.
        /// </summary>
        internal static string ElementsPerRound {
            get {
                return ResourceManager.GetString("ElementsPerRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four different.
        /// </summary>
        internal static string Elems_FourDifferent {
            get {
                return ResourceManager.GetString("Elems_FourDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three different.
        /// </summary>
        internal static string Elems_ThreeDifferent {
            get {
                return ResourceManager.GetString("Elems_ThreeDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two different.
        /// </summary>
        internal static string Elems_TwoDifferent {
            get {
                return ResourceManager.GetString("Elems_TwoDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire.
        /// </summary>
        internal static string Fire {
            get {
                return ResourceManager.GetString("Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ground.
        /// </summary>
        internal static string Ground {
            get {
                return ResourceManager.GetString("Ground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice.
        /// </summary>
        internal static string Ice {
            get {
                return ResourceManager.GetString("Ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tricks :.
        /// </summary>
        internal static string Tricks {
            get {
                return ResourceManager.GetString("Tricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three parched ground :(.
        /// </summary>
        internal static string Tricks_3ParchedGround {
            get {
                return ResourceManager.GetString("Tricks_3ParchedGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to press+press+press+press.
        /// </summary>
        internal static string Tricks_4Pressed {
            get {
                return ResourceManager.GetString("Tricks_4Pressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mu-Mu-Mu-Mu-Multi-Kill !!!.
        /// </summary>
        internal static string Tricks_5Kills {
            get {
                return ResourceManager.GetString("Tricks_5Kills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on itself....
        /// </summary>
        internal static string Tricks_CheckBox {
            get {
                return ResourceManager.GetString("Tricks_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A charcoal!.
        /// </summary>
        internal static string Tricks_FireCoal {
            get {
                return ResourceManager.GetString("Tricks_FireCoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wet ground???.
        /// </summary>
        internal static string Tricks_GroundWet {
            get {
                return ResourceManager.GetString("Tricks_GroundWet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandoned water :(.
        /// </summary>
        internal static string Tricks_NoFireForWater {
            get {
                return ResourceManager.GetString("Tricks_NoFireForWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push the ground!.
        /// </summary>
        internal static string Tricks_PushTheGround {
            get {
                return ResourceManager.GetString("Tricks_PushTheGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SPEED is fast ~~~.
        /// </summary>
        internal static string Tricks_SpeedFastWithWind {
            get {
                return ResourceManager.GetString("Tricks_SpeedFastWithWind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intense Wind ....
        /// </summary>
        internal static string Tricks_Wind5cm {
            get {
                return ResourceManager.GetString("Tricks_Wind5cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinch a Bio Element with two fingers to compress it!.
        /// </summary>
        internal static string TutorialBio {
            get {
                return ResourceManager.GetString("TutorialBio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect two Electricity Elements by pressing them at the same time!.
        /// </summary>
        internal static string TutorialElectricity2 {
            get {
                return ResourceManager.GetString("TutorialElectricity2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect three Electricity Elements by pressing them at the same time!.
        /// </summary>
        internal static string TutorialElectricity3 {
            get {
                return ResourceManager.GetString("TutorialElectricity3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press once on a Fire Element to ignite it!.
        /// </summary>
        internal static string TutorialFire {
            get {
                return ResourceManager.GetString("TutorialFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double press a Ground Element to explode it!.
        /// </summary>
        internal static string TutorialGround {
            get {
                return ResourceManager.GetString("TutorialGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At the top you can see the number of rounds in a level: there are three left!.
        /// </summary>
        internal static string TutorialRoundNumber {
            get {
                return ResourceManager.GetString("TutorialRoundNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At the bottom you can see the time allocated for a round: be careful, it will go faster!.
        /// </summary>
        internal static string TutorialRoundTimer {
            get {
                return ResourceManager.GetString("TutorialRoundTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be careful, there are three Elements ....
        /// </summary>
        internal static string TutorialThreeElems {
            get {
                return ResourceManager.GetString("TutorialThreeElems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be careful, there are two Elements ....
        /// </summary>
        internal static string TutorialTwoElems {
            get {
                return ResourceManager.GetString("TutorialTwoElems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move a Water element over one Fire Element to make it evaporate!.
        /// </summary>
        internal static string TutorialWater1 {
            get {
                return ResourceManager.GetString("TutorialWater1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move an Ice element over two Fire Elements to make it evaporate!.
        /// </summary>
        internal static string TutorialWater2 {
            get {
                return ResourceManager.GetString("TutorialWater2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move a Wind Element to scramble it!.
        /// </summary>
        internal static string TutorialWind {
            get {
                return ResourceManager.GetString("TutorialWind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels unlocked on Standard will be automaticaly unlocked on Easy.
        /// </summary>
        internal static string UnlockedLevels {
            get {
                return ResourceManager.GetString("UnlockedLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        internal static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind.
        /// </summary>
        internal static string Wind {
            get {
                return ResourceManager.GetString("Wind", resourceCulture);
            }
        }
    }
}
